/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:bbae2bac-bd4e-47b6-b2a0-b120b11268ce",// changed
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_ruTeKY48t",// changed
    "aws_user_pools_web_client_id": "25pv1q8b01sf82mkpsfkf7hu2k",// changed
    "oauth": {}
};


export default awsmobile;
